### ISSUE TITLE
bcm2835_init: Unable to open /dev/gpiomem: No such file or directory

### ISSUE THREAD

**Issue by ghost** [rsporny/homebridge-gpio-blinds#17]
Hi,

I installed this plugin through the homebridge web UI. 
Going back and forward between 'docker-compose logs -f' and  installing the missing dependencies, I'm now stuck. Here's the docker log file of homebridge.

Dependencies I've installed so far: 

- npm i rpio
- apt install gcc build-essentials

I'm running this on a raspberry pi zero.

```
homebridge_1  | [1/9/2019, 6:51:39 PM] Loading 0 platforms...
homebridge_1  | [1/9/2019, 6:51:39 PM] Loading 2 accessories...
homebridge_1  | [1/9/2019, 6:51:39 PM] [Slaapkamer straat] Initializing Blinds accessory...
homebridge_1  | bcm2835_init: Unable to open /dev/gpiomem: No such file or directory
homebridge_1  | 
homebridge_1  | /homebridge/node_modules/homebridge-gpio-blinds/node_modules/rpio/lib/rpio.js:104
homebridge_1  | 	return bindfunc(optarg);
homebridge_1  |         ^
homebridge_1  | Error: Could not initialize bcm2835 GPIO library
homebridge_1  |     at bindcall (/homebridge/node_modules/homebridge-gpio-blinds/node_modules/rpio/lib/rpio.js:104:9)
homebridge_1  |     at rpio.init (/homebridge/node_modules/homebridge-gpio-blinds/node_modules/rpio/lib/rpio.js:461:2)
homebridge_1  |     at new BlindsAccessory (/homebridge/node_modules/homebridge-gpio-blinds/index.js:61:8)
homebridge_1  |     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:29)
homebridge_1  |     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
homebridge_1  |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
homebridge_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
```

**Comment by rsporny** [comment]
Hi, looks like rpio cannot initialize. If you are using docker please see this issue https://github.com/jperkin/node-rpio/issues/79
